### ISSUE TITLE
possible eventemitter memory leak

### ISSUE THREAD

**Issue by slively** [deployd/deployd#206]
Anybody else gotten this warning?

windows server 2008 r2

node -v
v0.10.10

dpd --version
0.6.10
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added.
Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:160:15)
    at EventEmitter.once (events.js:179:8)
    at new Session (C:\pelr share\leadershipRounding\node_modules\deployd\lib\se
ssion.js:167:21)
    at C:\pelr share\leadershipRounding\node_modules\deployd\lib\session.js:74:3
9
    at C:\pelr share\leadershipRounding\node_modules\deployd\lib\db.js:345:11
    at C:\pelr share\leadershipRounding\node_modules\deployd\node_modules\mongod
b\lib\mongodb\collection.js:882:34
    at C:\pelr share\leadershipRounding\node_modules\deployd\node_modules\mongod
b\lib\mongodb\cursor.js:133:9
    at C:\pelr share\leadershipRounding\node_modules\deployd\node_modules\mongod
b\lib\mongodb\cursor.js:173:11
    at C:\pelr share\leadershipRounding\node_modules\deployd\node_modules\mongod
b\lib\mongodb\cursor.js:467:35
    at Cursor.close (C:\pelr share\leadershipRounding\node_modules\deployd\node_
modules\mongodb\lib\mongodb\cursor.js:687:5)
```

**Comment by NicolasRitouet** [comment]
Since it's an old issue and an old version on Deployd, I'll close the ticket.
Feel free to reopen it if the issue is still there.
