### ISSUE TITLE
"cannot write to IPC channel" error on Windows

### ISSUE THREAD

**Issue by dallonf** [deployd/deployd#230]
After a clean `git clone` and `npm install` of the master branch on Windows 8 (x64), attempting to run the `test-app` gives the following error:

    C:\Users\DallonF\devroot\deployd\test-app>node ..\bin\dpd
    starting deployd v0.6.11...

    C:\Users\DallonF\devroot\deployd\test-app>
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: write EPIPE - cannot write to IPC channel.
        at errnoException (child_process.js:977:11)
        at process.target.send (child_process.js:452:16)
        at Function.Monitor.createCommands (C:\Users\DallonF\devroot\deployd\lib\monitor.js:108:11)
        at Object.<anonymous> (C:\Users\DallonF\devroot\deployd\lib\start.js:18:9)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)

A quick search for the error reveals it has something to do with cluster.js, which isn't something I've used before.

**Comment by dallonf** [comment]
I think this one of the first things that got fixed during Deployd's revival (not sure which commit or PR, though). I'll close the ticket now.
