### ISSUE TITLE
Error in running integration tests

### ISSUE THREAD

**Issue by yoneal** [deployd/deployd#245]
The unit tests works fine but when i do:
```
cd test-app
dpd -o
```
The following error occurs:
```
Error loading resources:
Error: Cannot find type "Proxy" for resource proxy
    at Array.async.auto.instance [as 2] (/Users/neal/Projects/deployd/git/lib/config-loader.js:112:37)
    at listener (/Users/neal/Projects/deployd/git/node_modules/async/lib/async.js:412:46)
    at /Users/neal/Projects/deployd/git/node_modules/async/lib/async.js:371:17
    at Array.forEach (native)
    at _forEach (/Users/neal/Projects/deployd/git/node_modules/async/lib/async.js:26:24)
    at taskComplete (/Users/neal/Projects/deployd/git/node_modules/async/lib/async.js:370:13)
    at taskCallback (/Users/neal/Projects/deployd/git/node_modules/async/lib/async.js:396:21)
    at Array.async.auto.configJson [as 1] (/Users/neal/Projects/deployd/git/lib/config-loader.js:90:11)
    at listener (/Users/neal/Projects/deployd/git/node_modules/async/lib/async.js:412:46)
    at /Users/neal/Projects/deployd/git/node_modules/async/lib/async.js:371:17
```

I am running this on OS X 10, node 0.10.15, latest head of deployd and mongodb 2.4.5.

Or did I just miss something?

**Comment by NicolasRitouet** [comment]
fixed by #455
