### ISSUE TITLE
Tryng to login : get error

### ISSUE THREAD

**Issue by jfest** [deployd/deployd#534]
dpd : 0,8
mongodb : db version v2.0.6, pdfile version 4.5

Stacktrace : 

On login with correct credential >

POST /users/login TypeError: Not a string or buffer
    at TypeError (native)
    at Hmac.Hash.update (crypto.js:119:16)
    at UserCollection.hash (/usr/local/lib/node_modules/deployd/lib/resources/user-collection.js:243:44)
    at UserCollection.checkHash (/usr/local/lib/node_modules/deployd/lib/resources/user-collection.js:250:22)
    at /usr/local/lib/node_modules/deployd/lib/resources/user-collection.js:201:14
    at /usr/local/lib/node_modules/deployd/lib/db.js:397:9
    at handleCallback (/usr/local/lib/node_modules/deployd/node_modules/mongodb/lib/utils.js:93:12)
    at /usr/local/lib/node_modules/deployd/node_modules/mongodb/lib/collection.js:837:5
    at handleCallback (/usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:211:5)
    at Cursor.next (/usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:495:5)
    at /usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:438:12
    at queryCallback (/usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:192:5)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at Callbacks.emit (/usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:90:3)
    at null.messageHandler (/usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:219:23)
Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deployd.com/docs/basics/cli.html)

**Comment by andreialecu** [comment]
I think this can only happen if the password field is somehow empty in 
the database. Can you check your underlying Mongo db and see if password 
is actually set to anything?

**Comment by jfest** [comment]
Hello, is not empty : 
{ "displayName" : "lulu", "role" : "admin", "username" : "jsfest", "password" : "3288fb498d9da6ea6c4c3d1343803fcc4e04f34897feb28a857629a46e96c75f53dbaa404b40a19009098b88e16ab432890d184c7f49beba98ae7b52b53731c5a1eb66d6d66c899b7da7d6190da84af7ebb405c340e79a93f332aaf0a80b53663ed7fb69e6203b27abd7ec4e19b8c05aa3172dff4adf9f720688f7b9605baada599e31b80f2cff2cb45813fed09b7164b2291f3b3c9dfb3520e75234e8f485a5", "_id" : "12cbb9b3f044db91" }

**Comment by ericfong** [comment]
Cannot reproduce ...

**Comment by jfest** [comment]
Ok,
i have reinstall all, now it's ok :x
