### ISSUE TITLE
update issue from 0.8.0 -> 0.8.4

### ISSUE THREAD

**Issue by Kvarkas** [deployd/deployd#588]
Hello, I download installation pack from website, its installed and run fine, also I have shortcut Check for Updates, and once it run its give me error:
Latest version is 0.8.4
Updating Deployd...
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/automattic/socket.io) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/automattic/socket.io) undefined
npm ERR! git clone https://github.com/automattic/socket.io undefined
npm ERR! git clone https://github.com/automattic/socket.io undefined
{ [Error: not found: git] code: 'ENOGIT', parent: 'deployd' }

Press any key to continue...
Installed Deployd version 0.8.4

Press any key to continue...

**Comment by ericfong** [comment]
Are you using npm install ?

I think you better try with npm and please check git and github.io is
accessible from you server

On Fri, Jun 12, 2015 at 5:29 PM, Kvarkas <notifications@github.com> wrote:

> Hello, I download installation pack from website, its installed and run
> fine, also I have shortcut Check for Updates, and once it run its give me
> error:
> Latest version is 0.8.4
> Updating Deployd...
> npm WARN git config --get remote.origin.url returned wrong result (
> https://git
> hub.com/automattic/socket.io) undefined
> npm WARN git config --get remote.origin.url returned wrong result (
> https://git
> hub.com/automattic/socket.io) undefined
> npm ERR! git clone https://github.com/automattic/socket.io undefined
> npm ERR! git clone https://github.com/automattic/socket.io undefined
> { [Error: not found: git] code: 'ENOGIT', parent: 'deployd' }
>
> Press any key to continue...
> Installed Deployd version 0.8.4
>
> Press any key to continue...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployd/deployd/issues/588>.
>



-- 
Best Regards,
Eric Fong

**Comment by Kvarkas** [comment]
Hello, no I am using .exe file that was provided on website. I am Windows user. 

p.s. sorry for delay - just return from holidays.

**Comment by Kvarkas** [comment]
I think I found that was an issue for that. Then windows version is installed its put some modules under such path: C:\Program Files (x86)\Deployd\node_modules\deployd\node_modules however, on update process its delete that folder and not create it back. I try to install dpd (v 0.8.0) copy that folder out, update it (got same error) copy past that folder back - all working. So question is why update process don't recreate that folder back? As this is done under .exe file I can see that is wrong, so perhaps who compile it will know an answer...

**Comment by felipeplets** [comment]
Same here.
Thanks Kvarkas for sharing this work around.

Felipe Plets
Chief Executive Officer | CEO
T: +55 51 40421742 | M: +55 51 97252452
http://www.menvia.com/

**Comment by felipeplets** [comment]
Another point is that after updating my API is working but the dashboard not. 
I get the following error: 

`400ejs:58 56| 57| <script type="text/html" id="resource-sidebar-template"> >> 58| <% var type = types[resource.type]; %> 59| <% var isCurrent = resource.id === Context.resourceId %> 60| <li <%= isCurrent ? 'class="active"' : '' %>> 61| <a href="/dashboard/<%= resource.id %>" <%= type && type.dashboardPages ? 'class="pages-header"' : '' %>> types is not defined`

**Comment by Kvarkas** [comment]
You are right, don't test dashboard then post this, I think its something related to same folder file structure, investigating now...

**Comment by ericfong** [comment]
Would be nice, if any window users can help to make an PR on that. Thx

**Comment by Kvarkas** [comment]
I just try to use npm install and its also false with same errors, however full list are much bigger:
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

E:\!!!Rabochij\GitHub> cd..
E:\!!!Rabochij> cd dpd
E:\!!!Rabochij\dpd> npm install deployd -g
npm WARN `git config --get remote.origin.url` returned wrong result (https://git
hub.com/automattic/socket.io)
\


> kerberos@0.0.12 install C:\Users\Kvark\AppData\Roaming\npm\node_modules\deploy
d\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_modules\mongodb\nod
e_modules\mongodb-core\node_modules\kerberos>node "C:\Program Files\nodejs\node_
modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebui
ld
|


> bson-ext@0.1.10 install C:\Users\Kvark\AppData\Roaming\npm\node_modules\deploy
d\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\
bson-ext
> (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.
log) || (exit 0)

|
C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_modules\mongodb\nod
e_modules\mongodb-core\node_modules\bson\node_modules\bson-ext>node "C:\Program
Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\
node-gyp.js" clean
/
C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_modules\mongodb\nod
e_modules\mongodb-core\node_modules\bson\node_modules\bson-ext>node "C:\Program
Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\
node-gyp.js" configure --fallback-to-build --module=C:\Users\Kvark\AppData\Roami
ng\npm\node_modules\deployd\node_modules\mongodb\node_modules\mongodb-core\node_
modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --
module_path=C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_modules
\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build
\Release
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\
\Users\\Kvark\\AppData\\Roaming\\npm\\node_modules\\deployd\\node_modules\\mongo
db\\node_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bson-ext\\buil
d\\Release\\bson.node" "--module_name=bson" "--module_path=C:\\Users\\Kvark\\App
Data\\Roaming\\npm\\node_modules\\deployd\\node_modules\\mongodb\\node_modules\\
mongodb-core\\node_modules\\bson\\node_modules\\bson-ext\\build\\Release"
gyp ERR! cwd C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_module
s\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallb
ack-to-build --module=C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\no
de_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson
-ext\build\Release\bson.node --module_name=bson --module_path=C:\Users\Kvark\App
Data\Roaming\npm\node_modules\deployd\node_modules\mongodb\node_modules\mongodb-
core\node_modules\bson\node_modules\bson-ext\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Kvark\AppData\
Roaming\npm\node_modules\deployd\node_modules\mongodb\node_modules\mongodb-core\
node_modules\bson\node_modules\bson-ext\node_modules\node-pre-gyp\lib\util\compi
le.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_proces
s.js:833:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
 command "node" "C:\\Users\\Kvark\\AppData\\Roaming\\npm\\node_modules\\deployd\
\node_modules\\mongodb\\node_modules\\mongodb-core\\node_modules\\bson\\node_mod
ules\\bson-ext\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp.js" "install" "--f
allback-to-build"
node-pre-gyp ERR! cwd C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\no
de_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson
-ext
node-pre-gyp ERR! node -v v0.10.35
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\
Kvark\AppData\Roaming\npm\node_modules\deployd\node_modules\mongodb\node_modules
\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --
module_name=bson --module_path=C:\Users\Kvark\AppData\Roaming\npm\node_modules\d
eployd\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_mod
ules\bson-ext\build\Release' (1)

C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_modules\mongodb\nod
e_modules\mongodb-core\node_modules\bson\node_modules\bson-ext>node "C:\Program
Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\
node-gyp.js" rebuild
/


> bufferutil@1.1.0 install C:\Users\Kvark\AppData\Roaming\npm\node_modules\deplo
yd\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bu
fferutil
> node-gyp rebuild

-
C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_modules\socket.io\n
ode_modules\engine.io\node_modules\ws\node_modules\bufferutil>node "C:\Program F
iles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\n
ode-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_module
s\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0


> utf-8-validate@1.1.0 install C:\Users\Kvark\AppData\Roaming\npm\node_modules\d
eployd\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_module
s\utf-8-validate
> node-gyp rebuild

|
C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_modules\socket.io\n
ode_modules\engine.io\node_modules\ws\node_modules\utf-8-validate>node "C:\Progr
am Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\b
in\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_module
s\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
-


> ws@0.6.5 install C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_
modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\no
de_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd\node_modules\socket.io\n
ode_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild
C:\Users\Kvark\AppData\Roaming\npm\dpd -> C:\Users\Kvark\AppData\Roaming\npm\nod
e_modules\deployd\bin\dpd
deployd@0.8.4 C:\Users\Kvark\AppData\Roaming\npm\node_modules\deployd
├── opener@1.4.1
├── scrubber@0.0.0
├── validation@0.0.1
├── corser@2.0.0
├── step@0.0.5
├── underscore@1.8.3
├── async@0.9.2
├── wrench@1.5.8
├── qs@2.4.2
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── cookies@0.5.0 (keygrip@1.0.1)
├── filed@0.1.0 (mime@1.3.4)
├── semver@4.3.6
├── shelljs@0.4.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── send@0.12.3 (destroy@1.0.3, escape-html@1.0.1, ms@0.7.1, range-parser@1.0.2,
 fresh@0.2.4, depd@1.0.1, mime@1.3.4, on-finished@2.2.1, etag@1.6.0)
├── ejs@2.3.2
├── doh@0.0.4 (ejs@0.8.8)
├── bluebird@2.9.33
├── request@2.55.0 (aws-sign2@0.5.0, form-data@0.2.0, caseless@0.9.0, forever-ag
ent@0.6.1, tunnel-agent@0.4.1, oauth-sign@0.6.0, stringstream@0.0.4, isstream@0.
1.2, json-stringify-safe@5.0.1, node-uuid@1.4.3, mime-types@2.0.14, combined-str
eam@0.0.7, http-signature@0.10.1, bl@0.9.4, tough-cookie@2.0.0, hawk@2.3.1, har-
validator@1.8.0)
├── mongodb@2.0.33 (readable-stream@1.0.31, mongodb-core@1.1.32)
└── socket.io@1.3.2 (has-binary@0.1.6, debug@2.1.3, socket.io-parser@2.2.3, sock
et.io-adapter@0.3.1, engine.io@1.5.1, socket.io-client@1.3.2)
E:\!!!Rabochij\dpd>

**Comment by Kvarkas** [comment]
Ok, I am begginer in all of that, not sure that i PR correctly...
