### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by hjanuschka** [deployd/deployd#615]
stack trace of /col
on get:

    var self=this; 
    var myplugin=require("myplugin");

:

    ReferenceError: require is not defined
        at Object.eval (eval at <anonymous> (/opt/fxf/node_modules/deployd/lib/script.js:23:23), <anonymous>:2:11)
        at Script.runWithContext (/opt/fxf/node_modules/deployd/lib/script.js:30:15)
        at Script.run (/opt/fxf/node_modules/deployd/lib/script.js:151:10)
        at /opt/fxf/node_modules/deployd/lib/resources/collection/index.js:330:33
        at Array.forEach (native)
        at /opt/fxf/node_modules/deployd/lib/resources/collection/index.js:326:16
        at /opt/fxf/node_modules/deployd/lib/db.js:411:11
        at handleCallback (/opt/fxf/node_modules/deployd/node_modules/mongodb/lib/utils.js:95:12)
        at /opt/fxf/node_modules/deployd/node_modules/mongodb/lib/cursor.js:590:16
        at handleCallback (/opt/fxf/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
        at setCursorDeadAndNotified (/opt/fxf/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:424:3)
        at nextFunction (/opt/fxf/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:586:7)
        at Cursor.next (/opt/fxf/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:614:3)
        at fetchDocs (/opt/fxf/node_modules/deployd/node_modules/mongodb/lib/cursor.js:586:10)
        at /opt/fxf/node_modules/deployd/node_modules/mongodb/lib/cursor.js:608:7
        at handleCallback (/opt/fxf/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)

i have no clue why this one does not work, the exact same on get handler works on another dpd setup
all dpd version should be current master and node version matches, any hint on how to track down this issue?

ok when run with `dpd` cli it works, when using the production.js template from deployd.org - require is undefined

**Comment by Kvarkas** [comment]
Perhaps var myplugin=require('myplugin')?

**Comment by andreialecu** [comment]
@hjanuschka try installing [dpd-event-extension](https://www.npmjs.com/package/dpd-event-extension)

**Comment by hjanuschka** [comment]
you think this will help?
it only happens when i run dpd - as described here -> http://docs.deployd.com/docs/server/include-all.html using the production version.

if run via bin/dpd - the error is gone

**Comment by andreialecu** [comment]
Yes, it will help if you need a workaround. It provides require for you. 

We will fix this properly in a future release to be more consistent.

**Comment by hjanuschka** [comment]
ok tried that - and updated to master also - but now i get

    TypeError: Cannot call method 'createStore' of undefined
        at Object.eval (eval at <anonymous> (/opt/fxf/node_modules/deployd/lib/script.js:23:23), <anonymous>:4:28)
        at Script.runWithContext (/opt/fxf/node_modules/deployd/lib/script.js:30:15)
        at Script.run (/opt/fxf/node_modules/deployd/lib/script.js:151:10)
        at Script.run (/opt/fxf/node_modules/dpd-event-extension/event_extension.js:15:10)
        at /opt/fxf/node_modules/deployd/lib/resources/collection/index.js:330:33
        at Array.forEach (native)
        at /opt/fxf/node_modules/deployd/lib/resources/collection/index.js:326:16
        at /opt/fxf/node_modules/deployd/lib/db.js:411:11
        at handleCallback (/opt/fxf/node_modules/deployd/node_modules/mongodb/lib/utils.js:95:12)
        at /opt/fxf/node_modules/deployd/node_modules/mongodb/lib/cursor.js:590:16
        at handleCallback (/opt/fxf/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:234:5)
        at setCursorDeadAndNotified (/opt/fxf/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:424:3)
        at nextFunction (/opt/fxf/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:586:7)
        at Cursor.next (/opt/fxf/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:614:3)
        at fetchDocs (/opt/fxf/node_modules/deployd/node_modules/mongodb/lib/cursor.js:586:10)
        at /opt/fxf/node_modules/deployd/node_modules/mongodb/lib/cursor.js:608:7


using the following piece of code in the "on get"

    var users = process.server.createStore('users');

**Comment by hjanuschka** [comment]
ok solved by changing the line to

    var users = dpd.users.getResource().store;

are there any performance issues with that? or is it fine? -  would like to bypass the dpd.users.get() / internal client

**Comment by lawrence-eka** [comment]
Hi there, sorry to tump in into this old and closed issue, but could you please elaborate on what I should do after I installed the dpd-event-extension? I recently experienced the similar symptom i.e. require is not fdefined when I tried to call require() inside one of the resources event

**Comment by andreialecu** [comment]
@lawrence-eka just `npm install --save dpd-event-extension` should do. Make sure you have a package.json and dpd-event-extension is listed as a dependency.

**Comment by lawrence-eka** [comment]
So the dpd-event-extension should be included in deployd's package.json, I
suppose? I need to copy the files and might need to manually put them
because I work on a closed circuit network that doesnt allow me to connect
to the internet, hence npm install won't do.



On Dec 11, 2017 2:30 PM, "Andrei Alecu" <notifications@github.com> wrote:

@lawrence-eka <https://github.com/lawrence-eka> just npm install --save
dpd-event-extension should do. Make sure you have a package.json and
dpd-event-extension is listed as a dependency.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/deployd/deployd/issues/615#issuecomment-350684123>, or mute
the thread

**Comment by lawrence-eka** [comment]
I put dpd-event-extension as dependencies in deployd's package.json, it didn't solve the problem

Then I directly put the text of dpd-event-extension into deployd's index.js, now result is recognozed, but process.cwd() is no longer recognized as a function.
