### ISSUE TITLE
How to install deployd on google app engine VM instance(mongodb)

### ISSUE THREAD

**Issue by visikolkar** [deployd/deployd#621]
I'm trying to install the deployd to the google app engine VM instance. In the /var/www folder but when I run the command I get the error like this
visikolkar@mongo-db-cprb:/var/www$ dpd create hello
shell.js: internal error
Error: EACCES, permission denied 'hello'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at mkdirSyncRecursive (/home/visikolkar/.linuxbrew/lib/node_modules/deployd/node_modules/shelljs/src/mkdir.js:11:8)
    at /home/visikolkar/.linuxbrew/lib/node_modules/deployd/node_modules/shelljs/src/mkdir.js:63:7
    at Array.forEach (native)
    at _mkdir (/home/visikolkar/.linuxbrew/lib/node_modules/deployd/node_modules/shelljs/src/mkdir.js:48:8)
    at /home/visikolkar/.linuxbrew/lib/node_modules/deployd/node_modules/shelljs/src/common.js:186:23
    at Command.<anonymous> (/home/visikolkar/.linuxbrew/lib/node_modules/deployd/bin/dpd:54:5)
    at Command.listener (/home/visikolkar/.linuxbrew/lib/node_modules/deployd/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/home/visikolkar/.linuxbrew/lib/node_modules/deployd/node_modules/commander/index.js:610:12)
    at Command.parse (/home/visikolkar/.linuxbrew/lib/node_modules/deployd/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/home/visikolkar/.linuxbrew/lib/node_modules/deployd/bin/dpd:278:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

I don't understand is this app engine issue or deployd problem?? I did follow the docs mentioned in the http://docs.deployd.com/docs/server/your-server.html
Please help!

**Comment by visikolkar** [comment]
However If I run dpd create hello-world in the /home/visikolkar/ it works just fine. But I can't access the dashboard that way. I'm bit confused on this and much needed help here. Thanks in advance.

**Comment by ericfong** [comment]
Don't look like dpd problem?

**Comment by docnoe** [comment]
You probably don't have permissions to create files in /var/www.
