### ISSUE TITLE
Bug /users/me crash

### ISSUE THREAD

**Issue by guyskk** [deployd/deployd#640]
**First I create some users, then login with an user(saved cookie), then delete that user, at last, GET /users/me, the server crash**

Because I request  GET /users/me when webpage loaded, the server crash when I open my webpage.
As long as the cookie exist, the server will crash.

Here is the error messaes:
```
GET /users/me TypeError: Cannot read property 'username' of undefined
    at UserCollection.getUserAndPasswordHash (C:\Users\kk\AppData\Roaming\npm\no
de_modules\deployd\lib\resources\user-collection.js:297:46)
    at C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\lib\resources\user-c
ollection.js:115:29
    at C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\lib\db.js:385:11
    at handleCallback (C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\node
_modules\mongodb\lib\utils.js:95:12)
    at C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\node_modules\mongodb
\lib\collection.js:1122:5
    at handleCallback (C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\node
_modules\mongodb\lib\utils.js:95:12)
    at C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\node_modules\mongodb
\lib\cursor.js:597:5
    at handleCallback (C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\node
_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:244:5)
    at setCursorNotified (C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\n
ode_modules\mongodb\node_modules\mongodb-core\lib\cursor.js:558:3)
    at C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\node_modules\mongodb
\node_modules\mongodb-core\lib\cursor.js:661:16
    at queryCallback (C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\node_
modules\mongodb\node_modules\mongodb-core\lib\cursor.js:321:5)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at Callbacks.emit (C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\node
_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:95:3)
    at null.messageHandler (C:\Users\kk\AppData\Roaming\npm\node_modules\deployd
\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:243:23)

    at Socket.<anonymous> (C:\Users\kk\AppData\Roaming\npm\node_modules\deployd\
node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:262:
22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
bye
```

**Comment by lior-greenblatt** [comment]
+1

**Comment by ericfong** [comment]
anyone can help to make a PR?

**Comment by andreialecu** [comment]
Closed by https://github.com/deployd/deployd/pull/647
