### ISSUE TITLE
dpd > resources = crash

### ISSUE THREAD

**Issue by daslicht** [deployd/deployd#680]
Hi,
after creating a hello-world project and adding a resource and its property I get the following error when  I run the cli command  in the dpd> prompt:

```
resources
TypeError: Cannot read property 'type' of undefined - when initializing: Collection
    at /usr/lib/node_modules/deployd/lib/client/repl.js:54:17
    at Array.forEach (native)
    at Object.commands.resources (/usr/lib/node_modules/deployd/lib/client/repl.js:53:40)
    at tryCommand (/usr/lib/node_modules/deployd/lib/client/repl.js:81:23)
    at REPLServer.replEval [as eval] (/usr/lib/node_modules/deployd/lib/client/repl.js:23:5)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
    at emitKey (readline.js:1096:12)
    at ReadStream.onData (readline.js:841:14)
    at ReadStream.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:765:14)
bye
root@v22015072938226788:~/deployd/hello-world# 
```

**Comment by pkosenko** [comment]
I am having the same problem on Windows 7 using Node 0.10.35 and Deployd 0.8.7.  The server starts up and the "dashboard" command works and I can enter data, but I have no clue what "resources" I am supposed to get access to (I was hoping the database port, for example), since the "resources" command is a complete bust:

dpd > resources
resources
TypeError: Cannot read property 'type' of undefined
    at c:\Users\[user]\AppData\Roaming\npm\node_modules\deployd\lib\client\repl.js:54:17
    at Array.forEach (native)
    at Object.commands.resources (c:\Users\[user]\AppData\Roaming\npm\node_modules\deployd\lib\client\repl.js:53:40)
    at tryCommand (c:\Users\[user]\AppData\Roaming\npm\node_modules\deployd\lib\client\repl.js:81:23)
    at REPLServer.replEval (c:\Users\[user]\AppData\Roaming\npm\node_modules\deployd\lib\client\repl.js:23:5)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
    at ReadStream.emit (events.js:110:17)
    at readline.js:1175:14
    at Array.forEach (native)
dpd >
