### ISSUE TITLE
Cant start deployd on Centos

### ISSUE THREAD

**Issue by lindon88** [deployd/deployd#685]
Hello i have installed deployd globaly (npm install deployd -g). Then i have created project dpd create hello_world

Then I run this command (dpd -m) inside hello_world folder and i get this error
starting deployd v0.8.7...

child_process.js:923
  var r = this._handle.spawn(options);
                       ^
TypeError: Bad argument
    at ChildProcess.spawn (child_process.js:923:24)
    at exports.spawn (child_process.js:723:9)
    at Object.exports.restart (/usr/lib/node_modules/deployd/lib/util/mongod.js:38:14)
    at start (/usr/lib/node_modules/deployd/bin/dpd:149:16)
    at Object.<anonymous> (/usr/lib/node_modules/deployd/bin/dpd:280:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

Centos version CentOS release 6.5 (Final)
Node.js version 1.3.6

I also tried to install deploy locally but the same error.

**Comment by yusufiga** [comment]
Hi @lindon88 did you install the mongodb ? I'm not sure but I think you are getting this error because of the mongodb

**Comment by rgolea** [comment]
You should not start it from the dpd command. Please use [this gist](https://gist.github.com/andreialecu/a563c9a5ab7fdd7dc02f) to start a normal node instance. If node works on centos, so should deployd.

**Comment by rgolea** [comment]
Feel free to reopen this if needed.
