### ISSUE TITLE
Dashboard can't be accessed when using express-session

### ISSUE THREAD

**Issue by vafrcor** [deployd/deployd#715]
I tried at this condition:
* Ubuntu 14.04 
* Express 4.13.4
* Deployd 0.8.8
* Express Session 1.13.0
* Nodemon 1.8.1

This case based on this [tutorial](http://docs.deployd.com/docs/server/work-with-express.html)

When I tried to use express-session, dashboard page won't showed.
Nodemon didn't show any error.
Any help?
Thank you in advance.

**Comment by vafrcor** [comment]
Nodemon just display warnings as below:

```js
Warning: Promise.defer is deprecated and will be removed in a future version. Use new Promise instead.
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/lib/config-loader.js:154:38
From previous event:
  at addInternalResources (/opt/lampp/htdocs/deployd/myproject/node_modules/deployd/lib/config-loader.js:168:5)
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:760:23
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:166:37
  at fn (/opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:746:34)
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:1213:16
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:166:37
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:706:43
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:167:37
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:1209:30
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:52:16
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:361:13
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:52:16
  at done (/opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:246:17)
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:44:16
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:358:17
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/lib/config-loader.js:129:7
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:52:16
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:550:17
  at /opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:544:17
  at _arrayEach (/opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:85:13)
  at Immediate.taskComplete (/opt/lampp/htdocs/deployd/myproject/node_modules/deployd/node_modules/async/lib/async.js:543:13)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by moorthi07** [comment]
Do you still have this issue? 
Did you try 'npm update'
