### ISSUE TITLE
DPD vulnerable to unauthenticated DOS

### ISSUE THREAD

**Issue by p3nt4** [deployd/deployd#735]
Hi, 

My friend found an issue while pentesting my app. 
When putting a {} in the password field of the login function. Deployd fails to validate the type of the input and passes it to the hashing function that crashes. 

it results in the following error: 
`
{"message":"Not a string or buffer","status":500}
`
The server crashes with the following stack trace:
`
POST /users/login TypeError: Not a string or buffer
    at Hmac.Hash.update (crypto.js:209:17)
    at UserCollection.hash (/usr/local/lib/node_modules/deployd/lib/resources/user-collection.js:347:44)
    at UserCollection.checkHash (/usr/local/lib/node_modules/deployd/lib/resources/user-collection.js:362:22)
    at /usr/local/lib/node_modules/deployd/lib/resources/user-collection.js:264:14
    at /usr/local/lib/node_modules/deployd/lib/db.js:460:9
    at handleCallback (/usr/local/lib/node_modules/deployd/node_modules/mongodb/lib/utils.js:96:12)
    at /usr/local/lib/node_modules/deployd/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/usr/local/lib/node_modules/deployd/node_modules/mongodb/lib/utils.js:96:12)
    at /usr/local/lib/node_modules/deployd/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at nextFunction (/usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:683:5)
    at /usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:585:7
    at queryCallback (/usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:241:5)
    at b (domain.js:183:18)
    at Callbacks.emit (/usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/usr/local/lib/node_modules/deployd/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:358:23)
bye
`
UPDATE:
I added the following in my onbeforerequest event as a fix. 
`
cancelIf((ctx.url=='/login' && typeof ctx.body.password != 'string'),'Ashley, STOP THIS!',400);
`
And onPut and on Post:
`cancelIf(typeof ctx.body.password != 'string','Ashley, STOP THIS!',400);`
Thanks for the awesome work.

Cheers,
Louis

**Comment by fotoflo** [comment]
Love this issue! Thank you!!

**Comment by p3nt4** [comment]
Update
The previous code was breaking the GET/DELETE requests to the /users table.

This seems to be better:
`cancelIf(((ctx.method=='POST')||(ctx.method=='PUT') && typeof ctx.body.password != 'string'),'Ashley, STOP THIS!',400);`

**Comment by ash47** [comment]
@andreialecu Does your team request CVEs for vulnerabilities that are reported?
