### ISSUE TITLE
500TypeError: mime.lookup is not a function

### ISSUE THREAD

**Issue by chemyfio** [deployd/deployd#822]
I got an error it said ,

TypeError: mime.lookup is not a function
    at new File (/app/node_modules/filed/main.js:33:44)
    at module.exports (/app/node_modules/filed/main.js:201:10)
    at Dashboard.handle (/app/node_modules/deployd/lib/resources/dashboard.js:37:5)
    at /app/node_modules/deployd/lib/router.js:81:22
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

i dont know where the error is, i never got this error before?
so, could somebody help me with this.. i'm using deployd a couple times, it's always success. This is my first time got this error.. please help me Thankyou

**Comment by NicolasRitouet** [comment]
We have a [fix for that](https://github.com/deployd/dpd-dashboard/pull/3), I'll release a new version very soon.

**Comment by NicolasRitouet** [comment]
v0.8.10 has been released with a fix for this
