### ISSUE TITLE
console logs: ls: no such file or directory: resources/**/config.json with new install Deployd 1.1.1  

### ISSUE THREAD

**Issue by moorthi07** [deployd/deployd#841]
After installing deployd 1.1.1 and dpd-dashboard 1.
console logs: the below (but dashboard loads fine)
DPD Server is listening on port: 2404
ls: no such file or directory: resources/**/config.json
ls: no such file or directory: resources/**/config.json
ls: no such file or directory: resources/**/config.json
ls: no such file or directory: resources/**/config.json
ls: no such file or directory: resources/**/config.json

**Comment by andreialecu** [comment]
Is this with a new project without any resources yet added?

**Comment by moorthi07** [comment]
Yes. Just hitting url -  'localhost:2404' , logs the above message  one time.

but hitting http://localhost:2404/dashboard/ prints more than 10 times.
Seems to be the new dpd-dashboard issue.
Also I'm not able to make dpd-dashboard work with  npm link, I'm getting  a 404 @ http://localhost:2404/dashboard/  ( thought I see the folder created inside node_modules after running npm link dpd-dashboard )

**Comment by andreialecu** [comment]
You need to run `node` with the `--preserve-symlinks` flag in order to properly get `npm link`ed module recognized by deployd. Also, they need to probably be listed in `package.json`.

eg.
`node --preserve-symlinks server.js`

The warning can be safely ignored, once you add a resource it should disappear.

**Comment by moorthi07** [comment]
Thanks @andreialecu . But , dashboard partially loads and  throws error .

##node --preserve-symlinks server.js
MMU DPD Server is listening on port: 2404

GET /dashboard/stylesheets/style.css?1.1.1 TypeError: mime.lookup is not a function
    at new File (C:\Users\\Deployd\dpd_tutorial\node_modules\dpd-dashboard\node_modules\filed\main.js:33:44)
    at module.exports (C:\Users\\Deployd\dpd_tutorial\node_modules\dpd-dashboard\node_modules\filed\main.js:201:10)
    at Dashboard.handle (C:\Users\\Deployd\dpd_tutorial\node_modules\dpd-dashboard\dashboard.js:36:5)
    at C:\Users\\Deployd\dpd_tutorial\node_modules\deployd\lib\router.js:81:22
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

## Browser error:
ailed to load resource: the server responded with a status of 500 (Internal Server Error)
style.css Failed to load resource: net::ERR_CONNECTION_REFUSED
jquery-1.7.2.min.js Failed to load resource: net::ERR_CONNECTION_REFUSED
jquery.cookie.js Failed to load resource: net::ERR_CONNECTION_REFUSED
underscore-min.js Failed to load resource: net::ERR_CONNECTION_REFUSED
bootstrap.min.js Failed to load resource: net::ERR_CONNECTION_REFUSED
ui.js Failed to load resource: net::ERR_CONNECTION_REFUSED
ace.js Failed to load resource: net::ERR_CONNECTION_REFUSED
theme-deployd.js Failed to load resource: net::ERR_CONNECTION_REFUSED
prettify.js Failed to load resource: net::ERR_CONNECTION_REFUSED
mode-javascript.js Failed to load resource: net::ERR_CONNECTION_REFUSED
mode-json.js Failed to load resource: net::ERR_CONNECTION_REFUSED
dpd.js Failed to load resource: net::ERR_CONNECTION_REFUSED
events.js Failed to load resource: net::ERR_CONNECTION_REFUSED
sidebar.js Failed to load resource: net::ERR_CONNECTION_REFUSED
header.js Failed to load resource: net::ERR_CONNECTION_REFUSED
knockout-2.1.0.js Failed to load resource: net::ERR_CONNECTION_REFUSED
knockout.mapping.js Failed to load resource: net::ERR_CONNECTION_REFUSED
knockout-util.js Failed to load resource: net::ERR_CONNECTION_REFUSED
key-constants.js Failed to load resource: net::ERR_CONNECTION_REFUSED
jquery-ui-1.8.22.custom.min.js Failed to load resource: net::ERR_CONNECTION_REFUSED
util.js Failed to load resource: net::ERR_CONNECTION_REFUSED
Properties.js Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by andreialecu** [comment]
Did you run `npm install` in the `dpd-dashboard` folder?

Also try `npm install mime@1.4.0 --save` in the root project.

**Comment by moorthi07** [comment]
Great. `npm install mime@1.4.0 --save ` in the dpd-dashboard module worked.
And yes, dpd-dashboard - is a new install.
Thanks.
And ,
https://github.com/deployd/dpd-dashboard/blob/master/package.json - shows, mime in section -
```
  "resolutions": {
    "mime": "1.4.0"
  },
```
Its not actually installing that part .

So, where to update the docs? I'm not able to install docs because of gyp errors.  Pl. chk the issue as well. If I can install , I can fill in the docs.

**Comment by moorthi07** [comment]
@andreialecu  kudos for routing 'namespace/api' . Beautiful.

**Comment by YounesKeraressi** [comment]
thx @andreialecu
