### ISSUE TITLE
Deployd failed to start mongodb

### ISSUE THREAD

**Issue by kkrishnan90** [deployd/deployd#846]
I give this command to terminal to start a `dpd` project
`dpd start`
Then I get this 
`starting deployd
Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deployd.com/docs/basics/cli.html)`
Then I tried `dpd --mongod`
I get this 
```deployd CLI version 2.0.2
starting deployd
child_process.js:380
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:493:38)
    at Object.exports.restart (/usr/local/lib/node_modules/deployd-cli/lib/util/mongod.js:52:16)
    at Object.start (/usr/local/lib/node_modules/deployd-cli/lib/cli/start.js:107:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/deployd-cli/bin/dpd.js:59:40)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

This is happening only in deployd CLI version 2.0.2. May I know how to fix this ? I even tried `exporting the path` for mongod. But no luck... Anyone here to sort this or facing the same issue ?

**Comment by arturhood** [comment]
I had a similar issue, and it only worked if I started dpd using the [run script](http://docs.deployd.com/docs/server/include-all.html)

**Comment by mistrydhruti** [comment]
After creating deployd project
cd to newly created project directory press enter 
dpd --host "127.0.0.1" -P '27017' -n "mongodb" -u " " -s " "
add above line in cmd
